export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAILED = 'FETCH_PLAYERS_FAILED';

export const CREATE_PLAYER = 'CREATE_PLAYER';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILED = 'CREATE_PLAYER_FAILED';

export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_FAILED = 'UPDATE_PLAYER_FAILED';

export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const REMOVE_PLAYER_FAILED = 'REMOVE_PLAYER_FAILED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const UPDATE_SIZE = 'UPDATE_SIZE';
export const UPDATE_FROM = 'UPDATE_FROM';
export const UPDATE_SORTING = 'UPDATE_SORTING';
